filegroup(
    name = "srcs",
    srcs = [
        "Adaptor",
        "Controller",
        "Data",
        "Inheritance",
        "Json",
        "Pojo",
        "Raw",
        "Template",
    ],
    visibility = ["//visibility:public"],
)
