workspace(name = "examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

local_repository(
    name = "rules_stringtemplate",
    path = "..",
)

load("@rules_stringtemplate//stringtemplate:repositories.bzl", "rules_stringtemplate_dependencies")

rules_stringtemplate_dependencies("4")
