workspace(name = "examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

local_repository(
    name = "rules_stringtemplate",
    path = "..",
)

load("@rules_stringtemplate//stringtemplate:deps.bzl", "stringtemplate_dependencies")

stringtemplate_dependencies("4.1.0")
